refactor: store source metadata in concepts table
cancervariants/gene-normalization pull request #233
Opened 2023-08-14 16:16 UTC by jsstevenson

2023-08-18 18:11 UTC, korikuzma requested changes
Updating the aws ddbs won't be an issue, we can just manually insert the 4 metadata items. However, I do agree that we should wait until merging/releasing until the other 2 normalizers and metakb are updated with these changes.

2023-08-18 18:11 UTC, korikuzma commented on gene/database/dynamodb.py
> +            logger.info("Gene normalizer table is missing or unavailable.")
```suggestion
            logger.info(f"{self.gene_table} table is missing or unavailable.")
```

2023-08-18 18:16 UTC, korikuzma commented
If you really wanted to, you could just insert the metadata and keep the metadata tables until MetaKB is deployed with the updated versions

2023-08-21 20:35 UTC, jsstevenson commented
all of this sounds a little scary but I'll just push to a prerelease version for now

2023-08-26 11:35 UTC, korikuzma approved these changes

2023-09-05 13:27 UTC, merged