docs: incorporate Alex feedback
cancervariants/gene-normalization pull request #242
Opened 2023-08-25 00:40 UTC by jsstevenson

Following up on some stuff from Alex from a while back. 

* close #220 , combine installation pages, emphasize public REST API usage, move detailed instructions out of README
* Also close #124 , add usage instructions about what kinds of search terms work best

2023-08-30 14:07 UTC, korikuzma requested changes
small change

2023-08-30 14:07 UTC, korikuzma commented on README.md
> +>>> from gene.query import QueryHandler()
```suggestion
>>> from gene.query import QueryHandler
```

2023-08-31 00:31 UTC, jsstevenson commented on docs/source/normalizing_data/sources.rst
> +TODO do not merge before adding this part: describe source metadata
todo: address this

2023-08-31 00:32 UTC, jsstevenson commented on docs/source/usage.rst
todo -- the module/method link to create_db in this page isn't working. address this

2023-09-07 17:08 UTC, jsstevenson commented
staging version up at https://gene-normalizer--242.org.readthedocs.build/en/242/

2023-09-07 18:46 UTC, korikuzma approved these changes

2023-09-07 19:35 UTC, merged