enhancement!: break CLI update methods into reusable module
cancervariants/gene-normalization pull request #299
Opened 2023-11-21 01:24 UTC by jsstevenson

2023-11-21 17:54 UTC, jsstevenson commented
@korikuzma what would you think about shortening the options to `--all` and `--normalized`? eg

`gene-normalizer update --all` and `gene-normalizer update --normalized HGNC NCBI ensembl`

2023-11-21 18:02 UTC, korikuzma commented
> @korikuzma what would you think about shortening the options to `--all` and `--normalized`? eg
> 
> `gene-normalizer update --all` and `gene-normalizer update --normalized HGNC NCBI ensembl`

@jsstevenson to confirm, `all` would be all sources _and_ concept group creation? I'm not sure about the name `normalized` for the sources.

2023-11-29 13:47 UTC, jsstevenson commented
TODO:
* Circle back to kori comment
* Suppress noisy boto logs on CLI (?)

2023-12-13 19:36 UTC, korikuzma commented on src/gene/cli.py
> +        parsed_sources = list(set(parsed_sources))
I don't think it's necessary to cast back to list. We could just have `parsed_sources` be a set in L93

```suggestion
        parsed_sources = set(parsed_sources)
```

2023-12-13 19:36 UTC, korikuzma commented on src/gene/database/database.py
> +    :param env_name: name of database environment. Must be `"Prod"`, `"Dev"`, or
Could we use `AwsEnvName`?

2023-12-13 19:58 UTC, korikuzma requested changes

2023-12-13 19:58 UTC, korikuzma commented on src/gene/cli.py
> +        parsed_sources = set(parsed_sources)
Don't need this anymore
```suggestion
```

2023-12-13 20:00 UTC, jsstevenson commented on src/gene/cli.py
> +        parsed_sources = set(parsed_sources)
sigh

2023-12-13 20:02 UTC, korikuzma approved these changes
🚀

2023-12-13 20:06 UTC, merged